# Generated by Django 3.0.8 on 2020-07-30 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='like_thought', to='exam_app.User')),
                ('thought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_for', to='exam_app.User')),
            ],
        ),
    ]
