# Generated by Django 3.0.8 on 2020-07-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_thought'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='liked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
