# Generated by Django 3.0.8 on 2020-07-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_thought_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='liked',
            new_name='more_like',
        ),
    ]
